#spring.application.name=order-service
#spring.datasource.url=jdbc:mysql://user-service-db.cjcocai4if7n.ap-southeast-2.rds.amazonaws.com:3306/orders
#spring.datasource.username=orderservice
##spring.datasource.password=root@123
#spring.jpa.hibernate.ddl-auto=validate
#spring.jpa.show-sql=true
#spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL8Dialect
#spring.flyway.baseline-on-migrate=true
#spring.cloud.discovery.enabled=true
#server.port=8081
#inventory.service.url=http://INVENTORY-SERVICE
#spring.cloud.loadbalancer.ribbon.enabled=true
#eureka.client.service-url.defaultZone=http://localhost:8761/eureka
#management.endpoints.web.exposure.include=*

spring:
  application:
    name: order-service
  datasource:
    url: jdbc:mysql://localhost:3306/orders
    username: root
    password: root@123
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
  flyway:
    baseline-on-migrate: true
  cloud:
    discovery:
      enabled: true
    loadbalancer:
      ribbon:
        enabled: true
server:
  port: 8081

inventory:
  service:
    url: http://INVENTORY-SERVICE

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

management:
  endpoints:
    web:
      exposure:
        include=*:
